In [12]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import pandas as pd

import sympy as sp

In [13]:
df = pd.read_csv('face feature vectors.csv').drop('Unnamed: 0', axis=1)
#rename first column
df.rename(columns={'Unnamed: 1':'Gender'}, inplace=True)
print(df)

     Gender         0         1         2         3         4         5  \
0      male -0.066420  0.151611  0.027740  0.052771 -0.066105 -0.041232
1      male -0.030614  0.049667  0.008084 -0.050324  0.007649 -0.063818
2      male -0.096178  0.061127  0.035326 -0.035388 -0.090728 -0.018634
3      male -0.103057  0.085044  0.078333 -0.035873 -0.028163  0.004924
4      male -0.125815  0.120046  0.023131 -0.042901  0.038215 -0.049677
..      ...       ...       ...       ...       ...       ...       ...
795  female -0.164731  0.064301  0.058630 -0.017420 -0.157600 -0.022536
796  female -0.095308  0.051095  0.092913 -0.101745 -0.083153 -0.028159
797  female -0.202852  0.037039  0.079731 -0.047156 -0.140062 -0.080246
798  female -0.088300  0.063530  0.049627 -0.026011 -0.172773  0.086218
799  female -0.156201  0.055165  0.142716 -0.115393 -0.128982 -0.139830

            6         7         8  ...       118       119       120  \
0   -0.002637 -0.158467  0.130467  ...  0.025989 -0.001087  0.027260
1   -0.019530 -0.119905  0.186553  ...  0.044229 -0.023900 -0.028108
2   -0.024315 -0.139786  0.052211  ...  0.111141  0.059436 -0.029222
3    0.007829 -0.017016  0.114907  ...  0.100793 -0.002644 -0.023388
4   -0.054258 -0.130758  0.173457  ...  0.090197  0.067527  0.039926
..        ...       ...       ...  ...       ...       ...       ...
795  0.002864 -0.072739  0.030554  ...  0.095115  0.007198 -0.004655
796  0.009090 -0.114513  0.157421  ...  0.056078  0.119846  0.087470
797  0.057668 -0.122083  0.165443  ...  0.066954  0.035684 -0.023112
798  0.042710 -0.161852  0.185083  ...  0.039460  0.067547  0.040426
799 -0.037305 -0.101402  0.048473  ...  0.024955  0.066980 -0.002332

          121       122       123       124       125       126       127
0   -0.046754 -0.118619 -0.163774 -0.000590 -0.076400  0.107497  0.001567
1    0.040618 -0.146579 -0.141244  0.016162  0.017638  0.080610 -0.015930
2    0.042115 -0.222173 -0.116908  0.093428  0.017391  0.057652  0.086116
3    0.029497 -0.139830 -0.119243  0.005306 -0.015100  0.161575  0.062462
4    0.047469 -0.056852 -0.076700  0.004966  0.028171  0.026041  0.084135
..        ...       ...       ...       ...       ...       ...       ...
795  0.023957 -0.170753 -0.136630  0.041614  0.031600  0.019064  0.004384
796  0.017481 -0.096594 -0.084553  0.037709  0.030732 -0.083713  0.064970
797 -0.030452 -0.154243 -0.188270  0.071086  0.037384 -0.006257  0.039977
798  0.028007 -0.154515 -0.127736  0.046967  0.009701 -0.016942  0.048071
799 -0.045738 -0.110557 -0.014995 -0.002124 -0.010298 -0.028856  0.075323

[800 rows x 129 columns]

In [14]:
df

,Gender,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
0,male,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,0.130467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
1,male,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,0.186553,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
2,male,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,0.052211,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
3,male,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,0.114907,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
4,male,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,0.173457,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
796,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
797,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
798,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
799,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

In [15]:
df_train=pd.DataFrame()
df_test=pd.DataFrame()

In [16]:
for i in df['Gender'].unique():
    df_train = pd.concat([df_train, df[df['Gender'] == i].iloc[5:]],ignore_index=True)
    df_test = pd.concat([df_test, df[df['Gender'] == i].iloc[:5]],ignore_index=True)
    
df_train

,Gender,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
0,male,-0.149119,0.125288,0.142323,-0.009087,-0.031394,-0.123533,0.043598,-0.063999,0.162439,...,0.060833,0.089529,-0.034872,0.057080,-0.137162,-0.072522,0.052731,-0.141460,0.019018,0.085765
1,male,-0.139035,0.073513,-0.001770,-0.034225,-0.101610,0.065105,-0.014420,-0.054993,0.134674,...,0.081007,-0.002164,0.060377,0.080294,-0.139369,-0.150245,0.078657,0.024194,0.062180,0.036039
2,male,-0.074126,-0.000669,0.004166,-0.082413,-0.096091,-0.021992,0.009714,-0.056961,0.174237,...,0.050497,0.038932,0.023520,-0.090260,-0.147692,-0.008296,0.007609,-0.026687,-0.017523,-0.038310
3,male,-0.166220,0.042769,-0.031647,-0.036892,-0.143837,-0.040566,0.042541,-0.122923,0.188971,...,0.014732,-0.049135,0.081770,-0.027199,-0.096941,-0.094661,0.057797,-0.101063,0.061373,0.062176
4,male,-0.185770,0.154008,0.073184,-0.070829,-0.144617,-0.019732,-0.019418,-0.004675,0.152325,...,0.093317,0.035101,-0.147997,-0.046010,-0.087777,-0.100660,0.036190,0.012158,0.032304,0.085996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
786,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
787,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
788,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
789,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

In [29]:
y_train=df_train["Gender"]
X_train=df_train.drop(["Gender"],axis=1)
y_test=df_test["Gender"]
X_test=df_test.drop(["Gender"],axis=1)

print(X_test)

          0         1         2         3         4         5         6  \
0 -0.066420  0.151611  0.027740  0.052771 -0.066105 -0.041232 -0.002637
1 -0.030614  0.049667  0.008084 -0.050324  0.007649 -0.063818 -0.019530
2 -0.096178  0.061127  0.035326 -0.035388 -0.090728 -0.018634 -0.024315
3 -0.103057  0.085044  0.078333 -0.035873 -0.028163  0.004924  0.007829
4 -0.125815  0.120046  0.023131 -0.042901  0.038215 -0.049677 -0.054258
5  0.001747  0.185678  0.073260  0.042142 -0.088674  0.028186 -0.027830
6 -0.091598  0.095340  0.072125 -0.092276 -0.079953  0.047782 -0.004701
7 -0.018751  0.088572  0.068894 -0.065700 -0.115126  0.024339 -0.028420
8 -0.130889  0.093262  0.122244 -0.110014 -0.157625 -0.036781  0.073908
9 -0.037433  0.078158  0.118061 -0.117658 -0.194807 -0.045464 -0.014104

          7         8         9  ...       118       119       120       121  \
0 -0.158467  0.130467 -0.044872  ...  0.025989 -0.001087  0.027260 -0.046754
1 -0.119905  0.186553 -0.044821  ...  0.044229 -0.023900 -0.028108  0.040618
2 -0.139786  0.052211 -0.052085  ...  0.111141  0.059436 -0.029222  0.042115
3 -0.017016  0.114907 -0.056267  ...  0.100793 -0.002644 -0.023388  0.029497
4 -0.130758  0.173457 -0.011889  ...  0.090197  0.067527  0.039926  0.047469
5 -0.064211  0.097413 -0.010493  ...  0.123615  0.030036  0.041442 -0.012818
6 -0.092005  0.222913 -0.059830  ...  0.011370  0.144719  0.089139 -0.059767
7 -0.159320  0.164595 -0.116339  ...  0.010345  0.095309  0.012255 -0.033010
8 -0.098571  0.120419 -0.016198  ...  0.003229  0.049330  0.059733 -0.023820
9 -0.158824  0.159272 -0.112154  ...  0.043848 -0.009760  0.043486  0.020251

        122       123       124       125       126       127
0 -0.118619 -0.163774 -0.000590 -0.076400  0.107497  0.001567
1 -0.146579 -0.141244  0.016162  0.017638  0.080610 -0.015930
2 -0.222173 -0.116908  0.093428  0.017391  0.057652  0.086116
3 -0.139830 -0.119243  0.005306 -0.015100  0.161575  0.062462
4 -0.056852 -0.076700  0.004966  0.028171  0.026041  0.084135
5 -0.119177 -0.165786 -0.075368 -0.017690  0.067028  0.036452
6 -0.111235 -0.055420  0.006283  0.016900 -0.081676  0.022809
7 -0.097720 -0.218889  0.077764  0.045943  0.010856  0.100522
8 -0.098432 -0.034316  0.075131 -0.029204 -0.020707  0.031028
9 -0.115420 -0.040023  0.099409 -0.032240  0.037601 -0.020016

[10 rows x 128 columns]

In [30]:
def corr_coef(x, y):
    mean_x = x.mean()
    mean_y = y.mean()
    numerator = np.sum((x - mean_x) * (y - mean_y))
    denominator = np.sqrt(np.sum((x - mean_x) ** 2) * np.sum((y - mean_y) ** 2))
    corr = numerator / denominator
    return corr

In [31]:
def cov_matrix(df):
    corr_matrix = pd.DataFrame(index=df.columns, columns=df.columns)
    for col1 in df.columns:
        for col2 in df.columns:
            corr_matrix.loc[col1, col2] = corr_coef(df[col1], df[col2])

    corr_matrix = corr_matrix.astype(float)
    # Calculate the standard deviations of the variables
    std_devs = np.std(df, axis=0)

    # Calculate the covariance matrix
    covariance_matrix = corr_matrix * np.outer(std_devs, std_devs)
    
    return covariance_matrix

In [44]:
def multivariate_normal_pdf(x, mean, covariance):
    n = len(x)
    det_covariance =  sp.Matrix(covariance).det()
    inv_covariance = np.linalg.inv(covariance)
    x_minus_mean = x - mean
    exponent = -0.5 * np.dot(np.dot(x_minus_mean, inv_covariance), x_minus_mean)
    coefficient = 1 / ((2 * np.pi) ** (n / 2) * np.sqrt(det_covariance))
    return coefficient * np.exp(exponent)

def bayes_classifier(x):
    print(x)
    class_probs = []
    for i in range(len(np.unique(y_train))):
        class_mean = class_means[i]
        class_covariance = class_covs[i]
        class_probs.append(multivariate_normal_pdf(x, class_mean, class_covariance))
    return np.argmax(class_probs)

# Calculate the mean and covariance matrix for each class in the training set
class_means = []
class_covs = []
for class_label in np.unique(y_train):
    X_class = X_train[y_train == class_label]
    class_means.append(np.mean(X_class, axis=0))
    class_covs.append(cov_matrix(X_class))

# Classify the test feature vectors
y_pred = np.array([bayes_classifier(X_test.iloc[x].values) for x in range(len(X_test))])


# Calculate the accuracy of classification
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

[-0.06641996  0.15161145  0.02773961  0.05277055 -0.06610496 -0.04123223
 -0.00263749 -0.15846667  0.13046683 -0.04487232  0.27252948 -0.10790698
 -0.19001393 -0.14558613 -0.01268202  0.15481886 -0.24127068 -0.1629356
 -0.12037706 -0.04715446 -0.00402438  0.01086653  0.01380334  0.03386163
 -0.16508848 -0.35674018 -0.10496999 -0.08991732  0.16365613 -0.13833191
  0.01118823  0.00559458 -0.14461651 -0.07056299  0.08903963  0.04219805
 -0.01314605 -0.08854091  0.22637473  0.05762067 -0.18896441  0.0519334
  0.05043032  0.3500922   0.15261918  0.08452356  0.01909095 -0.07257793
  0.13797264 -0.2198092   0.08917116  0.11897166  0.17529357 -0.02023213
  0.17187869 -0.15235816 -0.05644821  0.18412034 -0.25527623  0.10844656
  0.06306192 -0.0626144  -0.00182713 -0.07117562  0.13016634  0.10455439
 -0.07404949 -0.09938268  0.20838721 -0.11574426 -0.03768751  0.06894148
 -0.01289451 -0.18084094 -0.31563017 -0.00855189  0.50753695  0.12787999
 -0.18813844 -0.02904258  0.02704281 -0.06494123  0.08049532  0.06643059
 -0.13093409 -0.06383382 -0.12337646  0.02297512  0.17648763  0.02352796
 -0.042136    0.14602598 -0.06014429 -0.04577906  0.0051162  -0.04026947
 -0.14653163  0.02020359 -0.07142203 -0.07093404  0.03937612 -0.07305673
  0.01310967  0.07319108 -0.17498381  0.11267292  0.05031709 -0.08770087
 -0.03392954  0.01855855 -0.08749244  0.07684974  0.16013944 -0.35951823
  0.22518858  0.17541894 -0.00395282  0.14298573  0.02598935 -0.00108702
  0.02726025 -0.04675362 -0.11861922 -0.16377406 -0.00059019 -0.07640016
  0.10749723  0.00156654]

TypeError: loop of ufunc does not support argument 0 of type Float which has no callable sqrt method

In [40]:
for x in range(100):
    print(X_train.iloc[x])

Gender        male
0        -0.149119
1         0.125288
2         0.142323
3        -0.009087
            ...
123      -0.072522
124       0.052731
125       -0.14146
126       0.019018
127       0.085765
Name: 0, Length: 129, dtype: object
Gender        male
0        -0.139035
1         0.073513
2         -0.00177
3        -0.034225
            ...
123      -0.150245
124       0.078657
125       0.024194
126        0.06218
127       0.036039
Name: 1, Length: 129, dtype: object
Gender        male
0        -0.074126
1        -0.000669
2         0.004166
3        -0.082413
            ...
123      -0.008296
124       0.007609
125      -0.026687
126      -0.017523
127       -0.03831
Name: 2, Length: 129, dtype: object
Gender        male
0         -0.16622
1         0.042769
2        -0.031647
3        -0.036892
            ...
123      -0.094661
124       0.057797
125      -0.101063
126       0.061373
127       0.062176
Name: 3, Length: 129, dtype: object
Gender        male
0         -0.18577
1         0.154008
2         0.073184
3        -0.070829
            ...
123       -0.10066
124        0.03619
125       0.012158
126       0.032304
127       0.085996
Name: 4, Length: 129, dtype: object
Gender        male
0         -0.10176
1         0.095119
2          0.02239
3         0.033455
            ...
123      -0.065993
124       0.086835
125       0.045227
126       0.134832
127       0.053776
Name: 5, Length: 129, dtype: object
Gender        male
0        -0.126957
1         0.065444
2         -0.01475
3        -0.062769
            ...
123      -0.084066
124      -0.004959
125      -0.025286
126      -0.003429
127       0.057033
Name: 6, Length: 129, dtype: object
Gender        male
0         0.021787
1         0.047769
2         0.031156
3        -0.036925
            ...
123      -0.179019
124      -0.045612
125      -0.052743
126       0.034252
127       0.046343
Name: 7, Length: 129, dtype: object
Gender        male
0        -0.091019
1         0.042462
2        -0.061052
3        -0.070249
            ...
123      -0.107603
124       0.031764
125      -0.026397
126       0.049204
127       -0.05045
Name: 8, Length: 129, dtype: object
Gender        male
0        -0.082929
1         0.058382
2         0.008007
3        -0.010675
            ...
123      -0.124878
124      -0.028671
125      -0.026378
126       0.048825
127      -0.025185
Name: 9, Length: 129, dtype: object
Gender        male
0        -0.190203
1         0.076832
2         0.175987
3        -0.008699
            ...
123      -0.018853
124       0.042929
125      -0.038633
126       0.054464
127       0.069612
Name: 10, Length: 129, dtype: object
Gender        male
0        -0.062974
1         0.073759
2         0.137618
3        -0.055731
            ...
123      -0.010455
124       0.002785
125      -0.012716
126       0.073269
127       0.023021
Name: 11, Length: 129, dtype: object
Gender        male
0        -0.136679
1         0.068268
2         0.074056
3        -0.005182
            ...
123      -0.036389
124       0.008624
125      -0.020781
126       0.001354
127       0.095373
Name: 12, Length: 129, dtype: object
Gender        male
0        -0.049137
1         0.056371
2         0.017949
3        -0.065481
            ...
123      -0.116696
124       0.048171
125      -0.020288
126       0.046044
127      -0.025426
Name: 13, Length: 129, dtype: object
Gender        male
0         -0.18873
1          0.04434
2         0.119253
3         0.028978
            ...
123      -0.105741
124       0.037274
125      -0.102401
126       0.094165
127       0.013822
Name: 14, Length: 129, dtype: object
Gender        male
0        -0.033949
1         0.085767
2         0.132219
3         0.033148
            ...
123      -0.020764
124      -0.050861
125      -0.034293
126       0.055814
127       0.030309
Name: 15, Length: 129, dtype: object
Gender        male
0        -0.105109
1         0.167064
2         0.029219
3        -0.081431
            ...
123      -0.129253
124       0.027648
125      -0.039727
126       0.033572
127       0.116667
Name: 16, Length: 129, dtype: object
Gender        male
0        -0.064001
1        -0.004413
2        -0.028249
3         0.020687
            ...
123      -0.164785
124      -0.103218
125      -0.047381
126       0.029801
127       0.074782
Name: 17, Length: 129, dtype: object
Gender        male
0        -0.078647
1         0.014206
2         0.061761
3         0.026074
            ...
123      -0.162934
124       0.000195
125      -0.015155
126       0.065621
127       0.084542
Name: 18, Length: 129, dtype: object
Gender        male
0        -0.091695
1         0.122976
2         0.055135
3         0.036042
            ...
123      -0.144918
124      -0.056404
125      -0.030166
126      -0.006177
127       0.079503
Name: 19, Length: 129, dtype: object
Gender        male
0        -0.076784
1         0.108963
2         0.038228
3        -0.011844
            ...
123      -0.177989
124       0.040264
125      -0.019998
126       0.145831
127       0.124811
Name: 20, Length: 129, dtype: object
Gender        male
0        -0.017511
1         0.008168
2         0.061076
3         0.012807
            ...
123      -0.103887
124      -0.077438
125      -0.102133
126      -0.004972
127       0.100798
Name: 21, Length: 129, dtype: object
Gender        male
0        -0.048254
1         0.075864
2         0.071926
3        -0.033895
            ...
123      -0.075559
124      -0.019623
125       0.043474
126       0.064333
127       0.133007
Name: 22, Length: 129, dtype: object
Gender        male
0        -0.032569
1         0.077142
2         0.088157
3        -0.028704
            ...
123      -0.085644
124      -0.005984
125       0.038765
126       0.053659
127       0.133053
Name: 23, Length: 129, dtype: object
Gender        male
0        -0.099643
1         0.090606
2         0.009562
3        -0.020513
            ...
123      -0.096291
124      -0.013736
125      -0.025313
126       0.051999
127        0.02964
Name: 24, Length: 129, dtype: object
Gender        male
0         -0.11672
1         0.167449
2          0.06912
3        -0.033608
            ...
123      -0.157018
124        0.00226
125      -0.039847
126       -0.04189
127       0.020369
Name: 25, Length: 129, dtype: object
Gender        male
0        -0.113274
1         0.136473
2         0.066517
3        -0.140593
            ...
123      -0.146603
124       0.087096
125       -0.00648
126       0.078441
127       0.013545
Name: 26, Length: 129, dtype: object
Gender        male
0         0.013488
1          0.11085
2         0.063272
3        -0.057173
            ...
123      -0.147207
124      -0.045869
125       0.013068
126      -0.042625
127       0.063321
Name: 27, Length: 129, dtype: object
Gender        male
0        -0.129356
1         0.169221
2         0.041399
3        -0.064334
            ...
123      -0.174909
124        0.02944
125      -0.041294
126      -0.054554
127       0.075798
Name: 28, Length: 129, dtype: object
Gender        male
0        -0.066711
1         0.103397
2         0.005007
3        -0.069394
            ...
123      -0.188909
124       0.015175
125      -0.029527
126       0.037779
127        0.09279
Name: 29, Length: 129, dtype: object
Gender        male
0        -0.095977
1          0.08044
2         0.032483
3        -0.090984
            ...
123      -0.110407
124       0.078945
125      -0.033068
126        0.03313
127       0.091589
Name: 30, Length: 129, dtype: object
Gender        male
0        -0.097318
1         0.191816
2         0.077546
3        -0.002779
            ...
123      -0.222627
124       0.100431
125       0.018471
126       0.007014
127       0.057591
Name: 31, Length: 129, dtype: object
Gender        male
0        -0.086336
1         0.130441
2         0.060532
3        -0.055945
            ...
123      -0.047597
124       0.007189
125      -0.061809
126      -0.021908
127       0.021273
Name: 32, Length: 129, dtype: object
Gender        male
0        -0.146177
1          0.16704
2         0.052353
3        -0.045109
            ...
123       -0.17257
124       0.027475
125       -0.14493
126      -0.029839
127       0.026894
Name: 33, Length: 129, dtype: object
Gender        male
0        -0.060285
1          0.06093
2        -0.003576
3         -0.06555
            ...
123      -0.188231
124       0.002251
125       0.057107
126       -0.03472
127       0.027246
Name: 34, Length: 129, dtype: object
Gender        male
0        -0.086765
1         0.126509
2         0.027112
3        -0.032537
            ...
123      -0.135494
124      -0.045036
125      -0.147682
126      -0.005413
127       0.020436
Name: 35, Length: 129, dtype: object
Gender        male
0         -0.02738
1        -0.019691
2         0.016464
3        -0.047405
            ...
123      -0.081492
124       0.060519
125       0.024497
126       0.025691
127      -0.018949
Name: 36, Length: 129, dtype: object
Gender        male
0        -0.207725
1         0.122044
2         0.078071
3        -0.007803
            ...
123      -0.058997
124       0.117271
125       -0.00097
126      -0.004478
127       0.039295
Name: 37, Length: 129, dtype: object
Gender        male
0        -0.016049
1         0.022821
2         0.016226
3        -0.010352
            ...
123      -0.158741
124      -0.007273
125       0.116822
126      -0.030098
127         0.0711
Name: 38, Length: 129, dtype: object
Gender        male
0         -0.15193
1         0.124074
2         0.137706
3         0.025432
            ...
123      -0.043706
124       0.120365
125       0.001901
126      -0.036444
127       0.013045
Name: 39, Length: 129, dtype: object
Gender        male
0        -0.038971
1         0.143643
2         0.087152
3         0.018372
            ...
123      -0.124474
124       0.037483
125      -0.006908
126       0.086569
127      -0.037493
Name: 40, Length: 129, dtype: object
Gender        male
0        -0.031653
1         0.029644
2         0.096382
3         0.054286
            ...
123      -0.088834
124      -0.084974
125       0.036541
126       0.047309
127       0.090924
Name: 41, Length: 129, dtype: object
Gender        male
0        -0.084964
1         0.003426
2          0.06576
3        -0.031551
            ...
123      -0.151035
124       0.041715
125       0.115718
126       0.035717
127       0.067838
Name: 42, Length: 129, dtype: object
Gender        male
0        -0.084836
1         0.038256
2         0.002396
3         0.008585
            ...
123      -0.095399
124       0.007875
125      -0.024889
126       0.002948
127      -0.040175
Name: 43, Length: 129, dtype: object
Gender        male
0        -0.120932
1        -0.042748
2         0.053667
3        -0.046537
            ...
123      -0.138354
124      -0.045181
125      -0.036791
126        0.01708
127       0.038815
Name: 44, Length: 129, dtype: object
Gender        male
0        -0.165479
1          0.07248
2         -0.00183
3        -0.031109
            ...
123      -0.057063
124        0.15041
125      -0.078686
126       0.080534
127       0.002482
Name: 45, Length: 129, dtype: object
Gender        male
0        -0.125155
1         0.102531
2         0.095313
3        -0.035054
            ...
123      -0.092981
124       0.013007
125      -0.029164
126       0.109714
127       0.026459
Name: 46, Length: 129, dtype: object
Gender        male
0        -0.159759
1         0.101592
2         0.030253
3        -0.025879
            ...
123        -0.0721
124       0.018295
125       0.003619
126      -0.037415
127       0.035039
Name: 47, Length: 129, dtype: object
Gender        male
0        -0.058257
1         0.069052
2         0.071726
3         0.013541
            ...
123      -0.062629
124       0.022461
125       0.094957
126       0.058868
127       0.044712
Name: 48, Length: 129, dtype: object
Gender        male
0        -0.063764
1         0.086003
2         0.100613
3        -0.119893
            ...
123      -0.187721
124      -0.017252
125      -0.030625
126      -0.042739
127       0.051441
Name: 49, Length: 129, dtype: object
Gender        male
0        -0.107761
1         0.029268
2        -0.044864
3        -0.050001
            ...
123      -0.126315
124       0.022422
125       0.078665
126       0.000491
127       0.058925
Name: 50, Length: 129, dtype: object
Gender        male
0        -0.135142
1         0.067487
2        -0.019681
3        -0.001153
            ...
123      -0.065272
124       0.011924
125       0.022666
126       0.012902
127       0.041253
Name: 51, Length: 129, dtype: object
Gender        male
0        -0.031251
1         0.068661
2         0.112962
3        -0.014464
            ...
123      -0.087015
124      -0.025674
125      -0.084301
126       0.019417
127       -0.00152
Name: 52, Length: 129, dtype: object
Gender        male
0        -0.076948
1         0.145278
2         0.097133
3        -0.013617
            ...
123      -0.086985
124       0.130445
125      -0.044034
126       0.067613
127      -0.005742
Name: 53, Length: 129, dtype: object
Gender        male
0        -0.134352
1         0.035646
2         0.011691
3        -0.031392
            ...
123      -0.090857
124       0.043808
125      -0.111035
126       0.047758
127       0.036748
Name: 54, Length: 129, dtype: object
Gender        male
0        -0.020647
1         0.143241
2         0.087103
3        -0.095617
            ...
123      -0.185211
124      -0.020558
125      -0.001499
126      -0.038564
127       0.094696
Name: 55, Length: 129, dtype: object
Gender        male
0         -0.07821
1         0.075056
2        -0.033998
3         0.041057
            ...
123      -0.235205
124      -0.057709
125       -0.05015
126        0.05355
127       0.036313
Name: 56, Length: 129, dtype: object
Gender        male
0        -0.142673
1         0.014069
2        -0.051367
3        -0.044873
            ...
123      -0.170171
124       0.094561
125       -0.09664
126       -0.00329
127       0.084762
Name: 57, Length: 129, dtype: object
Gender        male
0        -0.165212
1         0.090316
2         0.035709
3        -0.031836
            ...
123      -0.128554
124       0.041659
125      -0.062152
126       0.055808
127       0.049534
Name: 58, Length: 129, dtype: object
Gender        male
0        -0.115179
1         0.001288
2         0.109582
3        -0.084045
            ...
123      -0.128753
124      -0.004947
125      -0.024191
126       0.096267
127       0.074575
Name: 59, Length: 129, dtype: object
Gender        male
0        -0.133775
1         0.080219
2         0.110216
3         -0.04254
            ...
123      -0.088482
124        0.01537
125       0.026192
126       0.004013
127       0.031015
Name: 60, Length: 129, dtype: object
Gender        male
0        -0.056755
1         0.115038
2         0.031106
3        -0.079658
            ...
123      -0.083511
124       0.059715
125       0.040321
126       0.059147
127       0.039907
Name: 61, Length: 129, dtype: object
Gender        male
0        -0.048069
1         0.034583
2         0.013546
3        -0.017519
            ...
123      -0.123074
124       0.102031
125       0.041231
126       0.067558
127        0.01453
Name: 62, Length: 129, dtype: object
Gender        male
0        -0.164899
1         0.126855
2         0.039758
3        -0.040079
            ...
123      -0.105005
124       0.005231
125       0.003865
126      -0.055371
127      -0.031283
Name: 63, Length: 129, dtype: object
Gender        male
0        -0.011886
1         0.145334
2         0.065498
3        -0.039063
            ...
123      -0.076697
124      -0.009311
125      -0.016648
126       0.000941
127      -0.007355
Name: 64, Length: 129, dtype: object
Gender        male
0        -0.072646
1         0.194257
2        -0.014559
3        -0.094747
            ...
123      -0.034039
124        0.05959
125       0.003456
126      -0.043416
127      -0.005894
Name: 65, Length: 129, dtype: object
Gender        male
0        -0.036855
1          0.05142
2         0.036134
3        -0.067172
            ...
123      -0.203737
124      -0.035953
125      -0.038948
126       0.024832
127       0.017325
Name: 66, Length: 129, dtype: object
Gender        male
0         -0.18941
1         0.104026
2         0.052823
3        -0.062047
            ...
123      -0.124327
124       0.030742
125       0.027751
126       0.022483
127       0.060296
Name: 67, Length: 129, dtype: object
Gender        male
0        -0.121548
1         0.131948
2        -0.007673
3        -0.022577
            ...
123      -0.091013
124      -0.017775
125      -0.046168
126      -0.068045
127       0.006659
Name: 68, Length: 129, dtype: object
Gender        male
0        -0.082922
1         0.103446
2         0.009253
3        -0.028155
            ...
123      -0.143889
124       -0.00089
125      -0.028303
126       0.069872
127       0.015017
Name: 69, Length: 129, dtype: object
Gender        male
0         -0.15986
1         0.159709
2         0.128561
3         -0.06279
            ...
123       0.011518
124       0.120745
125      -0.058553
126       0.016339
127      -0.013499
Name: 70, Length: 129, dtype: object
Gender        male
0        -0.044593
1         0.058989
2         0.069767
3        -0.024187
            ...
123        -0.0924
124      -0.010315
125       0.078641
126       -0.01975
127        0.04626
Name: 71, Length: 129, dtype: object
Gender        male
0        -0.030141
1         0.060283
2         0.010675
3        -0.056153
            ...
123       -0.12792
124      -0.071506
125       0.011824
126       0.018341
127       0.018832
Name: 72, Length: 129, dtype: object
Gender        male
0        -0.082765
1         0.073796
2        -0.062747
3        -0.148209
            ...
123      -0.095871
124       0.015033
125      -0.000637
126        0.06034
127       0.091938
Name: 73, Length: 129, dtype: object
Gender        male
0        -0.064872
1         0.067913
2         0.118383
3        -0.010735
            ...
123       -0.10848
124       0.028295
125      -0.067567
126      -0.023062
127      -0.028125
Name: 74, Length: 129, dtype: object
Gender        male
0        -0.135702
1         0.115954
2        -0.006805
3        -0.058472
            ...
123       -0.12778
124       0.098835
125      -0.017442
126       0.042723
127       0.024744
Name: 75, Length: 129, dtype: object
Gender        male
0        -0.128137
1         0.164829
2         0.157991
3        -0.041897
            ...
123      -0.173553
124       0.033323
125      -0.101175
126       0.028953
127       0.016104
Name: 76, Length: 129, dtype: object
Gender        male
0         -0.08243
1         0.111478
2        -0.007818
3        -0.050955
            ...
123      -0.072364
124       0.081006
125       -0.02346
126       0.032347
127       0.059298
Name: 77, Length: 129, dtype: object
Gender        male
0        -0.064821
1         0.095219
2         0.083094
3        -0.116581
            ...
123       -0.06215
124       0.170976
125       0.073778
126      -0.015104
127       -0.02968
Name: 78, Length: 129, dtype: object
Gender        male
0        -0.121255
1         0.201606
2          0.04797
3        -0.026749
            ...
123      -0.109715
124      -0.037351
125       0.034241
126      -0.010788
127       0.096245
Name: 79, Length: 129, dtype: object
Gender        male
0        -0.031666
1         0.115614
2         0.088325
3         0.029765
            ...
123      -0.195783
124       0.008784
125      -0.000464
126       0.129752
127       0.057993
Name: 80, Length: 129, dtype: object
Gender        male
0        -0.035473
1         0.061604
2         0.025839
3        -0.100336
            ...
123      -0.198949
124       0.022294
125       0.037238
126      -0.043072
127      -0.006265
Name: 81, Length: 129, dtype: object
Gender        male
0        -0.093273
1          0.08051
2        -0.054033

In [117]:
comparing = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

print(comparing)

              Actual  Predicted
40       Iris-setosa          0
41       Iris-setosa          0
42       Iris-setosa          0
43       Iris-setosa          0
44       Iris-setosa          0
45       Iris-setosa          0
46       Iris-setosa          0
47       Iris-setosa          0
48       Iris-setosa          0
49       Iris-setosa          0
90   Iris-versicolor          1
91   Iris-versicolor          1
92   Iris-versicolor          1
93   Iris-versicolor          1
94   Iris-versicolor          1
95   Iris-versicolor          1
96   Iris-versicolor          1
97   Iris-versicolor          1
98   Iris-versicolor          1
99   Iris-versicolor          1
140   Iris-virginica          2
141   Iris-virginica          2
142   Iris-virginica          2
143   Iris-virginica          2
144   Iris-virginica          2
145   Iris-virginica          2
146   Iris-virginica          2
147   Iris-virginica          2
148   Iris-virginica          2
149   Iris-virginica          2